import { Team, UniformOrder, Match } from './types';

export const TEAMS: Record<string, Team> = {
  brasil: {
    id: 'brasil',
    name: 'Brasil',
    flag: '🇧🇷',
    flagEmoji: '🇧🇷',
    captain: 'A definir',
    totalPlayers: 10,
    colorHex: '#eab308',
    kitDescription: 'Camisa Amarela Ouro com detalhes verdes, calção azul e meias brancas',
    formation: '4-3-3',
    players: [
      { id: 'br-1', name: 'William', number: 1, position: 'Goleiro', goals: 0, assists: 0 },
      { id: 'br-2', name: 'Meirivan', number: 2, position: 'Defesa', goals: 0, assists: 0 },
      { id: 'br-3', name: 'Regis', number: 3, position: 'Defesa', goals: 0, assists: 0 },
      { id: 'br-4', name: 'Gui Izzo', number: 4, position: 'Defesa', goals: 0, assists: 0 },
      { id: 'br-5', name: 'Zaca', number: 5, position: 'Meio-campo', goals: 0, assists: 0 },
      { id: 'br-6', name: 'Léo Ramalho', number: 8, position: 'Meio-campo', goals: 0, assists: 0 },
      { id: 'br-7', name: 'Renan', number: 10, position: 'Meio-campo', goals: 0, assists: 0 },
      { id: 'br-8', name: 'Gui Carvalho', number: 7, position: 'Atacante', goals: 0, assists: 0 },
      { id: 'br-9', name: 'Pequeno', number: 9, position: 'Atacante', goals: 0, assists: 0 },
      { id: 'br-10', name: 'Danilo', number: 11, position: 'Atacante', goals: 0, assists: 0 },
    ],
  },
  argentina: {
    id: 'argentina',
    name: 'Argentina',
    flag: '🇦🇷',
    flagEmoji: '🇦🇷',
    captain: 'A definir',
    totalPlayers: 10,
    colorHex: '#38bdf8',
    kitDescription: 'Camisa Listrada Azul Celeste e Branca com números dourados e calção preto',
    formation: '4-3-3',
    players: [
      { id: 'arg-1', name: 'Douglas', number: 1, position: 'Goleiro', goals: 0, assists: 0 },
      { id: 'arg-2', name: 'Alisson', number: 2, position: 'Defesa', goals: 0, assists: 0 },
      { id: 'arg-3', name: 'Léo', number: 3, position: 'Defesa', goals: 0, assists: 0 },
      { id: 'arg-4', name: 'Joelci', number: 4, position: 'Defesa', goals: 0, assists: 0 },
      { id: 'arg-5', name: 'Guto', number: 6, position: 'Defesa', goals: 0, assists: 0 },
      { id: 'arg-6', name: 'Uesclei', number: 5, position: 'Meio-campo', goals: 0, assists: 0 },
      { id: 'arg-7', name: 'Vitor', number: 8, position: 'Meio-campo', goals: 0, assists: 0 },
      { id: 'arg-8', name: 'Bruno M', number: 10, position: 'Meio-campo', goals: 0, assists: 0 },
      { id: 'arg-9', name: 'Felipe', number: 9, position: 'Atacante', goals: 0, assists: 0 },
      { id: 'arg-10', name: 'Victor Guimarães', number: 11, position: 'Atacante', goals: 0, assists: 0 },
    ],
  },
  alemanha: {
    id: 'alemanha',
    name: 'Alemanha',
    flag: '🇩🇪',
    flagEmoji: '🇩🇪',
    captain: 'A definir',
    totalPlayers: 10,
    colorHex: '#ffffff',
    kitDescription: 'Camisa Branca com estampa Chevron Tricolor no peito e calção preto',
    formation: '4-3-3',
    players: [
      { id: 'de-1', name: 'Magrão', number: 1, position: 'Goleiro', goals: 0, assists: 0 },
      { id: 'de-2', name: 'Diego', number: 2, position: 'Defesa', goals: 0, assists: 0 },
      { id: 'de-3', name: 'Gil', number: 3, position: 'Defesa', goals: 0, assists: 0 },
      { id: 'de-4', name: 'Tico', number: 4, position: 'Defesa', goals: 0, assists: 0 },
      { id: 'de-5', name: 'Matheus Santana', number: 5, position: 'Meio-campo', goals: 0, assists: 0 },
      { id: 'de-6', name: 'Sunga', number: 8, position: 'Meio-campo', goals: 0, assists: 0 },
      { id: 'de-7', name: 'Caio', number: 10, position: 'Meio-campo', goals: 0, assists: 0 },
      { id: 'de-8', name: 'Renato', number: 7, position: 'Atacante', goals: 0, assists: 0 },
      { id: 'de-9', name: 'Marcelo', number: 9, position: 'Atacante', goals: 0, assists: 0 },
      { id: 'de-10', name: 'Douglas', number: 11, position: 'Atacante', goals: 0, assists: 0 },
    ],
  },
  franca: {
    id: 'franca',
    name: 'França',
    flag: '🇫🇷',
    flagEmoji: '🇫🇷',
    captain: 'A definir',
    totalPlayers: 9,
    colorHex: '#2563eb',
    kitDescription: 'Camisa Azul Royal com detalhe tricolor na gola e calção azul',
    formation: '4-3-3',
    players: [
      { id: 'fr-1', name: 'George', number: 1, position: 'Goleiro', goals: 0, assists: 0 },
      { id: 'fr-2', name: 'Shola', number: 2, position: 'Defesa', goals: 0, assists: 0 },
      { id: 'fr-3', name: 'Marcos', number: 3, position: 'Defesa', goals: 0, assists: 0 },
      { id: 'fr-4', name: 'Matheus Henrique', number: 5, position: 'Meio-campo', goals: 0, assists: 0 },
      { id: 'fr-5', name: 'Sapo', number: 8, position: 'Meio-campo', goals: 0, assists: 0 },
      { id: 'fr-6', name: 'Luis Jr', number: 10, position: 'Meio-campo', goals: 0, assists: 0 },
      { id: 'fr-7', name: 'Guaraná', number: 7, position: 'Atacante', goals: 0, assists: 0 },
      { id: 'fr-8', name: 'Jhon', number: 9, position: 'Atacante', goals: 0, assists: 0 },
      { id: 'fr-9', name: 'Luciano', number: 11, position: 'Atacante', goals: 0, assists: 0 },
    ],
  },
};

export const INITIAL_ORDERS: UniformOrder[] = [];

export const MATCHES: Match[] = [
  {
    id: 'm-1',
    teamA: 'brasil',
    teamB: 'argentina',
    date: '15/11/2026',
    time: 'A definir',
    status: 'Agendado',
    stadium: 'CETA — Bragança Paulista',
  },
  {
    id: 'm-2',
    teamA: 'franca',
    teamB: 'alemanha',
    date: '15/11/2026',
    time: 'A definir',
    status: 'Agendado',
    stadium: 'CETA — Bragança Paulista',
  },
];
