import { Team, UniformOrder, Match } from './types';

export const TEAMS: Record<string, Team> = {
  brasil: {
    id: 'brasil',
    name: 'Brasil',
    flag: '🇧🇷',
    flagEmoji: '🇧🇷',
    captain: 'Renan',
    totalPlayers: 10,
    colorHex: '#eab308',
    kitDescription: 'Camisa Amarela Ouro com detalhes verdes, calção azul e meias brancas',
    formation: '4-3-3',
    players: [
      { id: 'br-1', name: 'William', number: 1, position: 'Goleiro' },
      { id: 'br-2', name: 'Meirivan', number: 2, position: 'Defesa' },
      { id: 'br-3', name: 'Regis', number: 3, position: 'Defesa' },
      { id: 'br-4', name: 'Gui Izzo', number: 4, position: 'Defesa' },
      { id: 'br-5', name: 'Zaca', number: 5, position: 'Meio-campo' },
      { id: 'br-6', name: 'Léo Ramalho', number: 8, position: 'Meio-campo' },
      { id: 'br-7', name: 'Renan', number: 10, position: 'Meio-campo', isCaptain: true },
      { id: 'br-8', name: 'Gui Carvalho', number: 7, position: 'Atacante' },
      { id: 'br-9', name: 'Pequeno', number: 9, position: 'Atacante' },
      { id: 'br-10', name: 'Danilo', number: 11, position: 'Atacante' },
    ],
  },
  argentina: {
    id: 'argentina',
    name: 'Argentina',
    flag: '🇦🇷',
    flagEmoji: '🇦🇷',
    captain: 'Bruno M',
    totalPlayers: 10,
    colorHex: '#38bdf8',
    kitDescription: 'Camisa Listrada Azul Celeste e Branca com números dourados e calção preto',
    formation: '4-3-3',
    players: [
      { id: 'arg-1', name: 'Douglas', number: 1, position: 'Goleiro' },
      { id: 'arg-2', name: 'Alisson', number: 2, position: 'Defesa' },
      { id: 'arg-3', name: 'Léo', number: 3, position: 'Defesa' },
      { id: 'arg-4', name: 'Joelci', number: 4, position: 'Defesa' },
      { id: 'arg-5', name: 'Guto', number: 6, position: 'Defesa' },
      { id: 'arg-6', name: 'Uesclei', number: 5, position: 'Meio-campo' },
      { id: 'arg-7', name: 'Vitor', number: 8, position: 'Meio-campo' },
      { id: 'arg-8', name: 'Bruno M', number: 10, position: 'Meio-campo', isCaptain: true },
      { id: 'arg-9', name: 'Felipe', number: 9, position: 'Atacante' },
      { id: 'arg-10', name: 'Victor Guimarães', number: 11, position: 'Atacante' },
    ],
  },
  alemanha: {
    id: 'alemanha',
    name: 'Alemanha',
    flag: '🇩🇪',
    flagEmoji: '🇩🇪',
    captain: 'Caio',
    totalPlayers: 10,
    colorHex: '#ffffff',
    kitDescription: 'Camisa Branca com estampa Chevron Tricolor no peito e calção preto',
    formation: '4-3-3',
    players: [
      { id: 'de-1', name: 'Magrão', number: 1, position: 'Goleiro' },
      { id: 'de-2', name: 'Diego', number: 2, position: 'Defesa' },
      { id: 'de-3', name: 'Gil', number: 3, position: 'Defesa' },
      { id: 'de-4', name: 'Tico', number: 4, position: 'Defesa' },
      { id: 'de-5', name: 'Matheus Santana', number: 5, position: 'Meio-campo' },
      { id: 'de-6', name: 'Sunga', number: 8, position: 'Meio-campo' },
      { id: 'de-7', name: 'Caio', number: 10, position: 'Meio-campo', isCaptain: true },
      { id: 'de-8', name: 'Renato', number: 7, position: 'Atacante' },
      { id: 'de-9', name: 'Marcelo', number: 9, position: 'Atacante' },
      { id: 'de-10', name: 'Douglas', number: 11, position: 'Atacante' },
    ],
  },
  franca: {
    id: 'franca',
    name: 'França',
    flag: '🇫🇷',
    flagEmoji: '🇫🇷',
    captain: 'Luis Jr',
    totalPlayers: 9,
    colorHex: '#2563eb',
    kitDescription: 'Camisa Azul Royal com detalhe tricolor na gola e calção azul',
    formation: '4-3-3',
    players: [
      { id: 'fr-1', name: 'George', number: 1, position: 'Goleiro' },
      { id: 'fr-2', name: 'Shola', number: 2, position: 'Defesa' },
      { id: 'fr-3', name: 'Marcos', number: 3, position: 'Defesa' },
      { id: 'fr-4', name: 'Matheus Henrique', number: 5, position: 'Meio-campo' },
      { id: 'fr-5', name: 'Sapo', number: 8, position: 'Meio-campo' },
      { id: 'fr-6', name: 'Luis Jr', number: 10, position: 'Meio-campo', isCaptain: true },
      { id: 'fr-7', name: 'Guaraná', number: 7, position: 'Atacante' },
      { id: 'fr-8', name: 'Jhon', number: 9, position: 'Atacante' },
      { id: 'fr-9', name: 'Luciano', number: 11, position: 'Atacante' },
    ],
  },
};

export const INITIAL_ORDERS: UniformOrder[] = [
  {
    id: 'ord-101',
    teamId: 'brasil',
    playerName: 'Renan',
    jerseyName: 'RENAN',
    number: 10,
    size: 'G',
    position: 'Meio-campo',
    phone: '(11) 99999-1010',
    createdAt: '2026-08-10',
    status: 'Confirmado',
  },
  {
    id: 'ord-102',
    teamId: 'argentina',
    playerName: 'Bruno M',
    jerseyName: 'BRUNO M',
    number: 10,
    size: 'M',
    position: 'Meio-campo',
    phone: '(11) 98888-1010',
    createdAt: '2026-08-11',
    status: 'Em Confeccao',
  },
  {
    id: 'ord-103',
    teamId: 'alemanha',
    playerName: 'Caio',
    jerseyName: 'CAIO',
    number: 10,
    size: 'G',
    position: 'Meio-campo',
    phone: '(11) 97777-1010',
    createdAt: '2026-08-12',
    status: 'Confirmado',
  },
  {
    id: 'ord-104',
    teamId: 'franca',
    playerName: 'Luis Jr',
    jerseyName: 'LUIS JR',
    number: 10,
    size: 'M',
    position: 'Meio-campo',
    phone: '(11) 96666-0606',
    createdAt: '2026-08-14',
    status: 'Pendente',
  },
];

export const MATCHES: Match[] = [
  {
    id: 'm-1',
    teamA: 'brasil',
    teamB: 'argentina',
    scoreA: 3,
    scoreB: 2,
    date: '24 de Outubro, 2026',
    time: '16:00',
    status: 'Agendado',
    stadium: 'Estádio das Estrelas (Arena Beneficente)',
  },
  {
    id: 'm-2',
    teamA: 'franca',
    teamB: 'alemanha',
    scoreA: 1,
    scoreB: 1,
    date: '24 de Outubro, 2026',
    time: '18:00',
    status: 'Agendado',
    stadium: 'Estádio das Estrelas (Arena Beneficente)',
  },
  {
    id: 'm-3',
    teamA: 'brasil',
    teamB: 'franca',
    date: '25 de Outubro, 2026',
    time: '15:00',
    status: 'Agendado',
    stadium: 'Estádio das Estrelas (Arena Beneficente)',
  },
  {
    id: 'm-4',
    teamA: 'argentina',
    teamB: 'alemanha',
    date: '25 de Outubro, 2026',
    time: '17:30',
    status: 'Agendado',
    stadium: 'Estádio das Estrelas (Arena Beneficente)',
  },
];
